name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  publish:
    steps:
      - uses: ./.github/workflows/setup.yml
      - run: yarn test
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
