name: Publish plugin to npmjs

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: plugin
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
          cache-dependency-path: ./plugin/yarn.lock
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable
      - run: yarn && yarn build
      - run: yarn test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
