name: test 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    uses: plaidev/karte-expo-plugin/.github/workflows/setup.yml@main
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: yarn test
