name: test 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml@main
  test:
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        shell: bash
        working-directory: plugin
    steps:
      - run: yarn test
