name: test 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: plaidev/karte-expo-plugin/.github/workflows/setup.yml
      - run: yarn test
