name: test 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: plugin
    steps:
      - uses: actions/checkout@v3
      - name: test ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./plugin/yarn.lock
      - run: corepack enable
      - run: yarn && yarn build
      - run: yarn test
