name: test 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: ls
      - run: yarn test
